services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: residence_hub
      POSTGRES_PASSWORD: residence_hub_dev
      POSTGRES_DB: residence_hub
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
